Add support for animations
vnen/godot-tiled-importer pull request #141
Opened 2021-09-10 02:13 UTC by jakes1403

Added support for animations. The code could use some improvements, have not tested for multi-image tilesets but works fine when using a single image tileset.
Solves issue #19

2022-04-29 23:26 UTC, jonbonazza commented
@vnen can you please merge this? I've verified it works with the latest 3.4 release

2022-04-29 23:30 UTC, jakes1403 commented
Last commit here was 2019. At this point I gave up and just made a seperate addon.

2022-04-29 23:31 UTC, jonbonazza commented
Yea, Im in contact with @vnen in the godot dev chat. I think we should be able to get this merged.

2022-04-29 23:39 UTC, jakes1403 commented
If you want to talk about this fork in some more in detail with me, I pinged you on the Godot discord, and my username is Jakes1403#0269

2022-04-30 22:17 UTC, vnen requested changes

2022-04-30 22:17 UTC, vnen commented on README.md
> +Added animations.
It's better to drop the changes to `README` since they all mention the fork.

2022-04-30 22:17 UTC, vnen commented on addons/vnen.tiled_importer/tiled_map_reader.gd
> +
This is me being pedantic, but if you can remove the tabs from the empty line it would be great.

2022-04-30 22:19 UTC, vnen commented
If you prefer to open a new PR from a branch in your fork (instead of `master`), it's not an issue for me. I say that mostly because of the changes in `README.md` that you may still want to keep in your fork.

2022-05-04 00:22 UTC, jakes1403 commented
Made a new branch and the proposed changes are in there. #145

2022-05-04 21:44 UTC, vnen commented
Superseded by #145

2022-05-04 21:44 UTC, closed without merging