Fix tileset load error
vnen/godot-tiled-importer pull request #149
Opened 2022-05-20 05:22 UTC by univeous

Fixes #148.

2022-06-13 18:41 UTC, vnen requested changes

2022-06-14 03:50 UTC, univeous commented on addons/vnen.tiled_importer/tiled_map_reader.gd
> +							result.tile_set_name(gid, ts.tiles[rel_id].properties.name)
is it looks good now?

2022-06-17 17:35 UTC, vnen approved these changes

2022-06-17 17:35 UTC, merged

2022-06-17 17:35 UTC, vnen commented
Thanks!